require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClosingsController do

  # This should return the minimal set of attributes required to create a valid
  # Closing. As you add validations to Closing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2015-06-14 01:18:15" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClosingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all closings as @closings" do
      closing = Closing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:closings).should eq([closing])
    end
  end

  describe "GET show" do
    it "assigns the requested closing as @closing" do
      closing = Closing.create! valid_attributes
      get :show, {:id => closing.to_param}, valid_session
      assigns(:closing).should eq(closing)
    end
  end

  describe "GET new" do
    it "assigns a new closing as @closing" do
      get :new, {}, valid_session
      assigns(:closing).should be_a_new(Closing)
    end
  end

  describe "GET edit" do
    it "assigns the requested closing as @closing" do
      closing = Closing.create! valid_attributes
      get :edit, {:id => closing.to_param}, valid_session
      assigns(:closing).should eq(closing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Closing" do
        expect {
          post :create, {:closing => valid_attributes}, valid_session
        }.to change(Closing, :count).by(1)
      end

      it "assigns a newly created closing as @closing" do
        post :create, {:closing => valid_attributes}, valid_session
        assigns(:closing).should be_a(Closing)
        assigns(:closing).should be_persisted
      end

      it "redirects to the created closing" do
        post :create, {:closing => valid_attributes}, valid_session
        response.should redirect_to(Closing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved closing as @closing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Closing.any_instance.stub(:save).and_return(false)
        post :create, {:closing => { "date" => "invalid value" }}, valid_session
        assigns(:closing).should be_a_new(Closing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Closing.any_instance.stub(:save).and_return(false)
        post :create, {:closing => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested closing" do
        closing = Closing.create! valid_attributes
        # Assuming there are no other closings in the database, this
        # specifies that the Closing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Closing.any_instance.should_receive(:update).with({ "date" => "2015-06-14 01:18:15" })
        put :update, {:id => closing.to_param, :closing => { "date" => "2015-06-14 01:18:15" }}, valid_session
      end

      it "assigns the requested closing as @closing" do
        closing = Closing.create! valid_attributes
        put :update, {:id => closing.to_param, :closing => valid_attributes}, valid_session
        assigns(:closing).should eq(closing)
      end

      it "redirects to the closing" do
        closing = Closing.create! valid_attributes
        put :update, {:id => closing.to_param, :closing => valid_attributes}, valid_session
        response.should redirect_to(closing)
      end
    end

    describe "with invalid params" do
      it "assigns the closing as @closing" do
        closing = Closing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Closing.any_instance.stub(:save).and_return(false)
        put :update, {:id => closing.to_param, :closing => { "date" => "invalid value" }}, valid_session
        assigns(:closing).should eq(closing)
      end

      it "re-renders the 'edit' template" do
        closing = Closing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Closing.any_instance.stub(:save).and_return(false)
        put :update, {:id => closing.to_param, :closing => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested closing" do
      closing = Closing.create! valid_attributes
      expect {
        delete :destroy, {:id => closing.to_param}, valid_session
      }.to change(Closing, :count).by(-1)
    end

    it "redirects to the closings list" do
      closing = Closing.create! valid_attributes
      delete :destroy, {:id => closing.to_param}, valid_session
      response.should redirect_to(closings_url)
    end
  end

end
